---
- hosts: all
  tasks:
  - name: create directory
    file:
      pat: /home/ansible/testdirectory
      state: directory
  - name: create file
    file:
      path: /home/ansible/testfile
      state: touch
